;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="GameplayCue.DeathCue",DevComment="")
+GameplayTagList=(Tag="GameplayCue.DeathCue.FrostGiant",DevComment="")
+GameplayTagList=(Tag="GameplayCue.DeathCue.Guardian",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.MagicShield",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.MagicShield.PerfectBlock",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.MagicShield.SuccessBlock",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.MagicShield.WeaponClash",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.Rage.Activating",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.UnBlockableWarning",DevComment="")
+GameplayTagList=(Tag="GameplayCue.hitsound.Axe",DevComment="")
+GameplayTagList=(Tag="GameplayCue.hitsound.GuardianStick",DevComment="")

