;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Enemy.Ability.ShowHealthBar",DevComment="")
+GameplayTagList=(Tag="Enemy.Boss.Ability1",DevComment="")
+GameplayTagList=(Tag="Enemy.Boss.Attack1",DevComment="")
+GameplayTagList=(Tag="Enemy.Event.BossAbility1",DevComment="")
+GameplayTagList=(Tag="Enemy.Event.PoiseBreak",DevComment="")
+GameplayTagList=(Tag="Enemy.Status.PoiseBroken",DevComment="")
+GameplayTagList=(Tag="Enemy.Status.Stunned",DevComment="")
+GameplayTagList=(Tag="GameplayCue.DeathCue",DevComment="")
+GameplayTagList=(Tag="GameplayCue.DeathCue.FrostGiant",DevComment="")
+GameplayTagList=(Tag="GameplayCue.DeathCue.Guardian",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.MagicShield",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.MagicShield.PerfectBlock",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.MagicShield.SuccessBlock",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.MagicShield.WeaponClash",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.Rage.Activating",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FX.UnBlockableWarning",DevComment="")
+GameplayTagList=(Tag="GameplayCue.hitsound.Axe",DevComment="")
+GameplayTagList=(Tag="GameplayCue.hitsound.GuardianStick",DevComment="")
+GameplayTagList=(Tag="InputTag.E",DevComment="")
+GameplayTagList=(Tag="InputTag.R",DevComment="")
+GameplayTagList=(Tag="InputTag.Sword2.Finish",DevComment="")
+GameplayTagList=(Tag="Player.Ability.E",DevComment="")
+GameplayTagList=(Tag="Player.Ability.r",DevComment="")
+GameplayTagList=(Tag="Player.E",DevComment="")
+GameplayTagList=(Tag="Player.Event.ComboWindow.Close",DevComment="")
+GameplayTagList=(Tag="Player.Event.ComboWindow.Open",DevComment="")
+GameplayTagList=(Tag="Player.Event.SwitchSword2",DevComment="")
+GameplayTagList=(Tag="Player.Status.Attack3",DevComment="")
+GameplayTagList=(Tag="Player.Status.Attack5",DevComment="")
+GameplayTagList=(Tag="Player.Weapon.Sword",DevComment="")
+GameplayTagList=(Tag="Player.Weapon.Sword1",DevComment="")

